"""add phone number

Revision ID: 125c136367a9
Revises: 027ac4df2843
Create Date: 2022-07-06 14:12:04.535140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125c136367a9'
down_revision = '027ac4df2843'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
